import { WorkoutPlan, WorkoutDifficulty, WorkoutDuration } from '@/types/workout';
import { SpecificGoal } from '@/types/user';

export const PREDEFINED_PLANS: Record<string, Record<string, WorkoutPlan[]>> = {
  build_muscle: {
    beginner: [
      {
        id: 'bm-beginner-1',
        name: 'Beginner Muscle Builder',
        description: 'Perfect for those new to strength training, focusing on compound movements',
        difficulty: 'beginner' as WorkoutDifficulty,
        duration: '1_month' as WorkoutDuration,
        specificGoal: 'build_muscle',
    isAIGenerated: false,
    schedule: [
      {
        id: 'day-1',
            name: 'Day 1: Upper Body',
        exercises: [
          {
            id: 'ex-1',
            name: 'Push-ups',
                description: 'Lower body to ground, push back up',
            muscleGroup: 'chest',
            sets: 3,
                reps: 8,
            restTime: 60,
          },
          {
            id: 'ex-2',
                name: 'Dumbbell Rows',
                description: 'Row dumbbells to chest',
            muscleGroup: 'back',
                sets: 3,
                reps: 10,
                restTime: 60,
              },
              {
                id: 'ex-3',
                name: 'Dumbbell Shoulder Press',
                description: 'Press dumbbells overhead',
                muscleGroup: 'shoulders',
            sets: 3,
            reps: 8,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Lower Body',
            exercises: [
              {
                id: 'ex-4',
                name: 'Bodyweight Squats',
                description: 'Squat down and back up',
                muscleGroup: 'legs',
                sets: 3,
                reps: 15,
                restTime: 60,
              },
              {
                id: 'ex-5',
                name: 'Lunges',
                description: 'Step forward, lower body',
                muscleGroup: 'legs',
                sets: 3,
                reps: 12,
                restTime: 60,
              },
              {
                id: 'ex-6',
                name: 'Calf Raises',
                description: 'Raise heels up and down',
                muscleGroup: 'legs',
                sets: 3,
                reps: 20,
                restTime: 45,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
      {
        id: 'bm-beginner-2',
        name: 'Foundation Builder',
        description: 'Build a solid foundation with basic movements',
        difficulty: 'beginner' as WorkoutDifficulty,
        duration: '3_month' as WorkoutDuration,
        specificGoal: 'build_muscle',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Full Body',
            exercises: [
              {
                id: 'ex-1',
                name: 'Squats',
                description: 'Lower body by bending knees',
                muscleGroup: 'legs',
                sets: 3,
                reps: 12,
                restTime: 90,
              },
              {
                id: 'ex-2',
                name: 'Push-ups',
                description: 'Lower body to ground, push back up',
                muscleGroup: 'chest',
                sets: 3,
                reps: 10,
            restTime: 90,
              },
              {
                id: 'ex-3',
                name: 'Plank',
                description: 'Hold plank position',
                muscleGroup: 'core',
                sets: 3,
                reps: 30,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
    intermediate: [
      {
        id: 'bm-intermediate-1',
        name: 'Intermediate Muscle Builder',
        description: 'Progressive overload with compound and isolation exercises',
        difficulty: 'intermediate' as WorkoutDifficulty,
        duration: '3_month' as WorkoutDuration,
        specificGoal: 'build_muscle',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Chest & Triceps',
            exercises: [
              {
                id: 'ex-1',
                name: 'Bench Press',
                description: 'Lie on bench, lower bar to chest, press up',
                muscleGroup: 'chest',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-2',
                name: 'Incline Dumbbell Press',
                description: 'Press dumbbells on incline bench',
                muscleGroup: 'chest',
            sets: 3,
            reps: 10,
                restTime: 90,
              },
              {
                id: 'ex-3',
                name: 'Tricep Dips',
                description: 'Lower body using triceps, push back up',
                muscleGroup: 'arms',
                sets: 3,
                reps: 12,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Back & Biceps',
            exercises: [
          {
            id: 'ex-4',
                name: 'Pull-ups',
                description: 'Pull body up to bar using back muscles',
                muscleGroup: 'back',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-5',
                name: 'Barbell Rows',
                description: 'Row barbell to lower chest',
                muscleGroup: 'back',
                sets: 4,
                reps: 10,
                restTime: 90,
              },
              {
                id: 'ex-6',
            name: 'Bicep Curls',
                description: 'Curl dumbbells using biceps',
            muscleGroup: 'arms',
            sets: 3,
            reps: 12,
            restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Legs',
            exercises: [
              {
                id: 'ex-7',
                name: 'Squats',
                description: 'Lower body by bending knees, return to standing',
                muscleGroup: 'legs',
                sets: 4,
                reps: 10,
                restTime: 120,
              },
              {
                id: 'ex-8',
                name: 'Deadlifts',
                description: 'Lift barbell from ground to hip level',
                muscleGroup: 'legs',
                sets: 4,
                reps: 8,
                restTime: 180,
              },
              {
                id: 'ex-9',
                name: 'Leg Press',
                description: 'Press weight with legs on machine',
                muscleGroup: 'legs',
                sets: 3,
                reps: 12,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-4',
            name: 'Day 4: Shoulders',
            exercises: [
              {
                id: 'ex-10',
                name: 'Military Press',
                description: 'Press barbell overhead',
                muscleGroup: 'shoulders',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-11',
                name: 'Lateral Raises',
                description: 'Raise dumbbells to sides',
                muscleGroup: 'shoulders',
                sets: 3,
                reps: 12,
                restTime: 60,
              },
              {
                id: 'ex-12',
                name: 'Rear Delt Flyes',
                description: 'Fly dumbbells behind back',
                muscleGroup: 'shoulders',
                sets: 3,
                reps: 12,
                restTime: 60,
              },
        ],
        restDay: false,
          },
          {
            id: 'day-5',
            name: 'Day 5: Rest',
            exercises: [],
            restDay: true,
          },
    ],
  },
  {
        id: 'bm-intermediate-2',
        name: 'Strength & Size',
        description: 'Focus on both strength and muscle growth',
        difficulty: 'intermediate' as WorkoutDifficulty,
        duration: '6_month' as WorkoutDuration,
    specificGoal: 'build_muscle',
    isAIGenerated: false,
    schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Push',
            exercises: [
              {
                id: 'ex-1',
                name: 'Bench Press',
                description: 'Lie on bench, lower bar to chest, press up',
                muscleGroup: 'chest',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-2',
                name: 'Overhead Press',
                description: 'Press barbell overhead',
                muscleGroup: 'shoulders',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-3',
                name: 'Dips',
                description: 'Lower body using triceps',
                muscleGroup: 'arms',
                sets: 3,
                reps: 10,
                restTime: 90,
              },
            ],
            restDay: false,
          },
      {
        id: 'day-2',
            name: 'Day 2: Pull',
            exercises: [
              {
                id: 'ex-4',
                name: 'Deadlifts',
                description: 'Lift barbell from ground to hip level',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-5',
                name: 'Pull-ups',
                description: 'Pull body up to bar',
                muscleGroup: 'back',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-6',
                name: 'Barbell Rows',
                description: 'Row barbell to lower chest',
                muscleGroup: 'back',
                sets: 4,
                reps: 10,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Legs',
            exercises: [
              {
                id: 'ex-7',
                name: 'Squats',
                description: 'Lower body by bending knees',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-8',
                name: 'Romanian Deadlifts',
                description: 'Deadlift variation for hamstrings',
                muscleGroup: 'legs',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-9',
                name: 'Leg Press',
                description: 'Press weight with legs',
                muscleGroup: 'legs',
                sets: 3,
                reps: 12,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-4',
            name: 'Day 4: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
    advanced: [
      {
        id: 'bm-advanced-1',
        name: 'Advanced Bodybuilding',
        description: 'High volume training for maximum muscle growth',
        difficulty: 'advanced' as WorkoutDifficulty,
        duration: '6_month' as WorkoutDuration,
        specificGoal: 'build_muscle',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Chest',
            exercises: [
              {
                id: 'ex-1',
                name: 'Bench Press',
                description: 'Lie on bench, lower bar to chest, press up',
                muscleGroup: 'chest',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-2',
                name: 'Incline Bench Press',
                description: 'Press on incline bench',
                muscleGroup: 'chest',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-3',
                name: 'Dumbbell Flyes',
                description: 'Fly dumbbells in arc motion',
                muscleGroup: 'chest',
                sets: 3,
                reps: 12,
                restTime: 90,
              },
              {
                id: 'ex-4',
                name: 'Dips',
                description: 'Lower body using triceps',
                muscleGroup: 'arms',
                sets: 3,
                reps: 10,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Back',
        exercises: [
          {
            id: 'ex-5',
                name: 'Deadlifts',
                description: 'Lift barbell from ground to hip level',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-6',
                name: 'Pull-ups',
                description: 'Pull body up to bar',
                muscleGroup: 'back',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-7',
                name: 'Barbell Rows',
                description: 'Row barbell to lower chest',
                muscleGroup: 'back',
                sets: 4,
                reps: 10,
                restTime: 90,
              },
              {
                id: 'ex-8',
                name: 'Lat Pulldowns',
                description: 'Pull bar down to chest',
                muscleGroup: 'back',
                sets: 3,
                reps: 12,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Shoulders',
            exercises: [
              {
                id: 'ex-9',
                name: 'Military Press',
                description: 'Press barbell overhead',
                muscleGroup: 'shoulders',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-10',
                name: 'Lateral Raises',
                description: 'Raise dumbbells to sides',
                muscleGroup: 'shoulders',
                sets: 4,
                reps: 12,
                restTime: 60,
              },
              {
                id: 'ex-11',
                name: 'Rear Delt Flyes',
                description: 'Fly dumbbells behind back',
                muscleGroup: 'shoulders',
                sets: 4,
                reps: 12,
                restTime: 60,
              },
              {
                id: 'ex-12',
                name: 'Upright Rows',
                description: 'Row barbell to chin',
                muscleGroup: 'shoulders',
                sets: 3,
                reps: 10,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-4',
            name: 'Day 4: Arms',
            exercises: [
              {
                id: 'ex-13',
                name: 'Close-Grip Bench Press',
                description: 'Bench press with close grip',
                muscleGroup: 'arms',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-14',
                name: 'Bicep Curls',
                description: 'Curl dumbbells using biceps',
                muscleGroup: 'arms',
                sets: 4,
                reps: 12,
                restTime: 60,
              },
              {
                id: 'ex-15',
                name: 'Tricep Extensions',
                description: 'Extend arms overhead',
                muscleGroup: 'arms',
                sets: 4,
                reps: 12,
                restTime: 60,
              },
              {
                id: 'ex-16',
                name: 'Hammer Curls',
                description: 'Curl dumbbells with hammer grip',
                muscleGroup: 'arms',
                sets: 3,
                reps: 12,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-5',
            name: 'Day 5: Legs',
            exercises: [
              {
                id: 'ex-17',
            name: 'Squats',
                description: 'Lower body by bending knees',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-18',
                name: 'Romanian Deadlifts',
                description: 'Deadlift variation for hamstrings',
                muscleGroup: 'legs',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-19',
                name: 'Leg Press',
                description: 'Press weight with legs',
            muscleGroup: 'legs',
            sets: 4,
            reps: 12,
            restTime: 90,
          },
          {
                id: 'ex-20',
                name: 'Leg Extensions',
                description: 'Extend legs on machine',
            muscleGroup: 'legs',
            sets: 3,
                reps: 15,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-6',
            name: 'Day 6: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
  },
  weight_loss: {
    beginner: [
      {
        id: 'wl-beginner-1',
        name: 'Beginner Fat Loss',
        description: 'Simple cardio and bodyweight exercises for weight loss',
        difficulty: 'beginner' as WorkoutDifficulty,
        duration: '1_month' as WorkoutDuration,
        specificGoal: 'weight_loss',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Cardio',
            exercises: [
              {
                id: 'ex-1',
                name: 'Walking',
                description: 'Walk at moderate pace',
                muscleGroup: 'cardio',
                sets: 1,
                reps: 30,
                restTime: 0,
              },
              {
                id: 'ex-2',
                name: 'Jumping Jacks',
                description: 'Jump while raising arms and legs',
                muscleGroup: 'cardio',
                sets: 3,
                reps: 20,
                restTime: 30,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Bodyweight',
            exercises: [
              {
                id: 'ex-3',
                name: 'Push-ups',
                description: 'Lower body to ground, push back up',
                muscleGroup: 'chest',
                sets: 3,
                reps: 8,
                restTime: 60,
              },
              {
                id: 'ex-4',
                name: 'Squats',
                description: 'Lower body by bending knees',
            muscleGroup: 'legs',
            sets: 3,
            reps: 15,
                restTime: 60,
              },
              {
                id: 'ex-5',
                name: 'Plank',
                description: 'Hold plank position',
                muscleGroup: 'core',
                sets: 3,
                reps: 30,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
    intermediate: [
      {
        id: 'wl-intermediate-1',
        name: 'Intermediate Fat Loss',
        description: 'HIIT and strength training for maximum fat burn',
        difficulty: 'intermediate' as WorkoutDifficulty,
        duration: '3_month' as WorkoutDuration,
    specificGoal: 'weight_loss',
    isAIGenerated: false,
    schedule: [
      {
            id: 'day-1',
            name: 'Day 1: HIIT Cardio',
        exercises: [
          {
                id: 'ex-1',
            name: 'Burpees',
                description: 'Squat, jump, push-up, jump',
                muscleGroup: 'full_body',
                sets: 3,
                reps: 15,
                restTime: 45,
              },
              {
                id: 'ex-2',
                name: 'Mountain Climbers',
                description: 'Alternate knee to chest',
            muscleGroup: 'full_body',
            sets: 3,
                reps: 30,
                restTime: 30,
              },
              {
                id: 'ex-3',
                name: 'Jump Squats',
                description: 'Squat then jump',
                muscleGroup: 'legs',
                sets: 3,
                reps: 20,
                restTime: 30,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Strength',
            exercises: [
              {
                id: 'ex-4',
                name: 'Squats',
                description: 'Lower body by bending knees',
                muscleGroup: 'legs',
                sets: 4,
                reps: 15,
                restTime: 60,
              },
              {
                id: 'ex-5',
                name: 'Push-ups',
                description: 'Lower body to ground, push back up',
                muscleGroup: 'chest',
                sets: 3,
                reps: 12,
                restTime: 45,
              },
              {
                id: 'ex-6',
                name: 'Plank',
                description: 'Hold plank position',
            muscleGroup: 'core',
            sets: 3,
                reps: 45,
                restTime: 30,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Cardio',
            exercises: [
              {
                id: 'ex-7',
                name: 'Running',
                description: 'Run at moderate pace',
            muscleGroup: 'cardio',
                sets: 1,
            reps: 30,
                restTime: 0,
              },
              {
                id: 'ex-8',
                name: 'Cycling',
                description: 'Cycle at high intensity',
                muscleGroup: 'cardio',
                sets: 1,
                reps: 20,
                restTime: 0,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-4',
            name: 'Day 4: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
    advanced: [
      {
        id: 'wl-advanced-1',
        name: 'Advanced Fat Loss',
        description: 'High-intensity circuit training for rapid fat loss',
        difficulty: 'advanced' as WorkoutDifficulty,
        duration: '6_month' as WorkoutDuration,
        specificGoal: 'weight_loss',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Circuit Training',
            exercises: [
  {
    id: 'ex-1',
                name: 'Burpees',
                description: 'Squat, jump, push-up, jump',
                muscleGroup: 'full_body',
                sets: 4,
                reps: 20,
                restTime: 30,
              },
              {
                id: 'ex-2',
                name: 'Mountain Climbers',
                description: 'Alternate knee to chest',
                muscleGroup: 'full_body',
                sets: 4,
                reps: 40,
                restTime: 30,
              },
              {
                id: 'ex-3',
                name: 'Jump Squats',
                description: 'Squat then jump',
                muscleGroup: 'legs',
                sets: 4,
                reps: 25,
                restTime: 30,
              },
              {
                id: 'ex-4',
    name: 'Push-ups',
                description: 'Lower body to ground, push back up',
                muscleGroup: 'chest',
                sets: 4,
                reps: 15,
                restTime: 30,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Strength',
            exercises: [
              {
                id: 'ex-5',
                name: 'Deadlifts',
                description: 'Lift barbell from ground to hip level',
                muscleGroup: 'legs',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-6',
                name: 'Bench Press',
                description: 'Lie on bench, lower bar to chest, press up',
    muscleGroup: 'chest',
                sets: 4,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-7',
                name: 'Squats',
                description: 'Lower body by bending knees',
                muscleGroup: 'legs',
                sets: 4,
    reps: 12,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Cardio',
            exercises: [
              {
                id: 'ex-8',
                name: 'Sprint Intervals',
                description: 'Sprint for 30 seconds, walk for 30 seconds',
                muscleGroup: 'cardio',
                sets: 10,
                reps: 30,
                restTime: 30,
              },
              {
                id: 'ex-9',
                name: 'Cycling',
                description: 'Cycle at high intensity',
                muscleGroup: 'cardio',
                sets: 1,
                reps: 30,
                restTime: 0,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-4',
            name: 'Day 4: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
  },
  increase_strength: {
    beginner: [
      {
        id: 'is-beginner-1',
        name: 'Beginner Strength',
        description: 'Focus on learning proper form and building basic strength',
        difficulty: 'beginner' as WorkoutDifficulty,
        duration: '3_month' as WorkoutDuration,
        specificGoal: 'increase_strength',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Full Body',
            exercises: [
              {
                id: 'ex-1',
    name: 'Squats',
                description: 'Lower body by bending knees',
    muscleGroup: 'legs',
    sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-2',
                name: 'Push-ups',
                description: 'Lower body to ground, push back up',
                muscleGroup: 'chest',
                sets: 3,
                reps: 8,
                restTime: 90,
  },
  {
    id: 'ex-3',
    name: 'Plank',
                description: 'Hold plank position',
    muscleGroup: 'core',
    sets: 3,
    reps: 30,
                restTime: 60,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
    intermediate: [
      {
        id: 'is-intermediate-1',
        name: 'Intermediate Strength',
        description: 'Progressive overload with compound movements',
        difficulty: 'intermediate' as WorkoutDifficulty,
        duration: '6_month' as WorkoutDuration,
        specificGoal: 'increase_strength',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Deadlift Focus',
            exercises: [
              {
                id: 'ex-1',
                name: 'Deadlifts',
                description: 'Lift barbell from ground to hip level',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-2',
                name: 'Romanian Deadlifts',
                description: 'Deadlift variation with focus on hamstrings',
                muscleGroup: 'legs',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-3',
                name: 'Good Mornings',
                description: 'Bend forward with barbell on shoulders',
                muscleGroup: 'legs',
                sets: 3,
                reps: 10,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Bench Press Focus',
            exercises: [
              {
                id: 'ex-4',
                name: 'Bench Press',
                description: 'Press barbell from chest',
                muscleGroup: 'chest',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-5',
                name: 'Incline Bench Press',
                description: 'Press on incline bench',
                muscleGroup: 'chest',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-6',
                name: 'Dips',
                description: 'Lower body using triceps',
                muscleGroup: 'arms',
                sets: 3,
                reps: 8,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
    advanced: [
      {
        id: 'is-advanced-1',
        name: 'Advanced Strength',
        description: 'Powerlifting-style training for maximum strength',
        difficulty: 'advanced' as WorkoutDifficulty,
        duration: '6_month' as WorkoutDuration,
        specificGoal: 'increase_strength',
        isAIGenerated: false,
        schedule: [
          {
            id: 'day-1',
            name: 'Day 1: Deadlift',
            exercises: [
              {
                id: 'ex-1',
                name: 'Deadlifts',
                description: 'Lift barbell from ground to hip level',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-2',
                name: 'Romanian Deadlifts',
                description: 'Deadlift variation for hamstrings',
                muscleGroup: 'legs',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-3',
                name: 'Good Mornings',
                description: 'Bend forward with barbell on shoulders',
                muscleGroup: 'legs',
                sets: 3,
                reps: 10,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-2',
            name: 'Day 2: Bench Press',
            exercises: [
              {
                id: 'ex-4',
                name: 'Bench Press',
                description: 'Press barbell from chest',
                muscleGroup: 'chest',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-5',
                name: 'Incline Bench Press',
                description: 'Press on incline bench',
                muscleGroup: 'chest',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-6',
                name: 'Dips',
                description: 'Lower body using triceps',
                muscleGroup: 'arms',
                sets: 3,
                reps: 8,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-3',
            name: 'Day 3: Rest',
            exercises: [],
            restDay: true,
          },
          {
            id: 'day-4',
            name: 'Day 4: Squat',
            exercises: [
              {
                id: 'ex-7',
                name: 'Squats',
                description: 'Lower body by bending knees',
                muscleGroup: 'legs',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-8',
                name: 'Front Squats',
                description: 'Squat with barbell in front',
                muscleGroup: 'legs',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-9',
                name: 'Box Jumps',
                description: 'Jump onto box and back down',
                muscleGroup: 'legs',
                sets: 3,
                reps: 8,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-5',
            name: 'Day 5: Overhead Press',
            exercises: [
              {
                id: 'ex-10',
                name: 'Military Press',
                description: 'Press barbell overhead',
                muscleGroup: 'shoulders',
                sets: 5,
                reps: 5,
                restTime: 180,
              },
              {
                id: 'ex-11',
                name: 'Push Press',
                description: 'Press with leg drive',
                muscleGroup: 'shoulders',
                sets: 3,
                reps: 8,
                restTime: 120,
              },
              {
                id: 'ex-12',
                name: 'Pull-ups',
                description: 'Pull body up to bar',
                muscleGroup: 'back',
                sets: 3,
                reps: 8,
                restTime: 90,
              },
            ],
            restDay: false,
          },
          {
            id: 'day-6',
            name: 'Day 6: Rest',
            exercises: [],
            restDay: true,
          },
        ],
      },
    ],
  },
};

export const getPredefinedPlans = (goal: SpecificGoal, difficulty: WorkoutDifficulty): WorkoutPlan[] => {
  try {
    console.log('🔍 Looking for plans with goal:', goal, 'difficulty:', difficulty);
    
    const goalPlans = PREDEFINED_PLANS[goal];
    if (!goalPlans) {
      console.log('⚠️ No plans found for goal:', goal);
      return [];
    }
    
    const difficultyPlans = goalPlans[difficulty];
    if (!difficultyPlans) {
      console.log('⚠️ No plans found for difficulty:', difficulty, 'in goal:', goal);
      return [];
    }
    
    console.log('✅ Found', difficultyPlans.length, 'plans for', goal, difficulty);
    return difficultyPlans;
  } catch (error) {
    console.error('❌ Error in getPredefinedPlans:', error);
    return [];
  }
};

export const getAllPredefinedPlans = (): WorkoutPlan[] => {
  console.log('🔍 Getting all predefined plans...');
  const allPlans: WorkoutPlan[] = [];
  
  Object.values(PREDEFINED_PLANS).forEach(goalPlans => {
    if (goalPlans && typeof goalPlans === 'object') {
      Object.values(goalPlans).forEach(difficultyPlans => {
        if (Array.isArray(difficultyPlans)) {
          allPlans.push(...difficultyPlans);
        }
      });
    }
  });
  
  console.log('📊 Total predefined plans found:', allPlans.length);
  if (allPlans.length > 0) {
    console.log('📋 First plan:', allPlans[0]?.name);
    console.log('📋 First plan structure:', allPlans[0]);
  }
  
  return allPlans;
}; 