# Generated by Django 5.2.3 on 2025-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=20)),
                ('starting_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ending_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('starting_body_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ending_body_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('body_fat_change', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('total_workouts', models.PositiveIntegerField(default=0)),
                ('total_workout_time', models.PositiveIntegerField(default=0)),
                ('average_workout_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_workout_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('workout_consistency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_worked_out', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Goal'), ('measurement', 'Measurement Goal'), ('strength', 'Strength Goal'), ('endurance', 'Endurance Goal'), ('body_composition', 'Body Composition Goal')], max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_date', models.DateField()),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('left_arm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('right_arm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('left_thigh', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('right_thigh', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('shoulders', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('calves', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('body_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/front/')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/back/')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/side/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'progress_entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_duration', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('total_days', models.PositiveIntegerField()),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('workouts_completed', models.PositiveIntegerField(default=0)),
                ('total_workout_time', models.PositiveIntegerField(default=0)),
                ('average_workout_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workout_progress',
            },
        ),
    ]
