# Generated by Django 5.2.3 on 2025-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reasoning', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('workout_plan', 'Workout Plan'), ('exercise', 'Exercise'), ('nutrition', 'Nutrition'), ('lifestyle', 'Lifestyle'), ('recovery', 'Recovery')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('user_feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('workout_plan', 'Workout Plan Generation'), ('recommendation', 'Workout Recommendation'), ('exercise_suggestion', 'Exercise Suggestion'), ('progress_analysis', 'Progress Analysis')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt', models.TextField()),
                ('user_context', models.JSONField(default=dict)),
                ('ai_response', models.JSONField(blank=True, default=dict, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('user_feedback', 'User Feedback'), ('workout_completion', 'Workout Completion'), ('progress_data', 'Progress Data'), ('user_preference', 'User Preference')], max_length=30)),
                ('data_content', models.JSONField()),
                ('user_profile_snapshot', models.JSONField(default=dict)),
                ('data_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_used_for_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_training_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('workout_generator', 'Workout Plan Generator'), ('recommendation_engine', 'Recommendation Engine'), ('progress_analyzer', 'Progress Analyzer')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('user_satisfaction_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_versions',
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
    ]
